CREATE TABLE IF NOT EXISTS HOMEWORLD (
  ID   				INTEGER IDENTITY PRIMARY KEY,
  NAME 				VARCHAR(80),
  ROTATIONPERIOD    INTEGER,
  ORBITALPERIOD     INTEGER,
  DIAMETER          INTEGER,
  CLIMATE 			VARCHAR(255),
  GRAVITY 			VARCHAR(255),
  TERRAIN 			VARCHAR(255),
  SURFACEWATER      INTEGER,
  POPULATION        INTEGER
);
CREATE INDEX HOMEWORLD_ID ON HOMEWORLD (ID);

CREATE TABLE IF NOT EXISTS SWHERO (
  ID         	INTEGER IDENTITY PRIMARY KEY,
  NAME       	VARCHAR(30),
  HEIGHT	 	INTEGER,
  MASS		 	INTEGER,
  HAIRCOLOR  	VARCHAR(20),
  SKINCOLOR  	VARCHAR(20),
  EYECOLOR   	VARCHAR(20),
  BIRTHYEAR  	VARCHAR(30),
  GENDER     	VARCHAR(20),
  HOMEWORLD_ID  INTEGER,
  FOREIGN KEY (HOMEWORLD_ID) REFERENCES HOMEWORLD(ID)
);
CREATE INDEX SWHERO_ID ON SWHERO (ID);

CREATE TABLE IF NOT EXISTS STARSHIPS (
  ID         			INTEGER IDENTITY PRIMARY KEY,
  NAME 					VARCHAR(30),
  MODEL  				VARCHAR(255),
  MANUFACTURER  		VARCHAR(255),
  COSTINCREDITS 		BIGINT,
  LENGTHSHIP       		INTEGER,
  MAXATMOSPHERICSPEED   INTEGER,
  CREW       			VARCHAR(255),
  PASSENGERS       		INTEGER,
  CARGOCAPACITY       	BIGINT,
  CONSUMABLES       	VARCHAR(30),
  HYPERDRIVERATING      VARCHAR(255),
  MGLT       			INTEGER,
  STARSHIPCLASS  		VARCHAR(255),
  SWHERO_ID             INTEGER,
  FOREIGN KEY (SWHERO_ID) REFERENCES SWHERO(ID)
);
CREATE INDEX STARSHIPS_ID ON STARSHIPS (ID);


